### ISSUE TITLE
Reduce reliance on dev versions of packages

### ISSUE THREAD

**Issue by Robinlovelace** [geocompx/geocompkg#40]
We still rely on 4 packages not on CRAN:

```
    mlr-org/mlr3extralearners,
    mlr-org/mlr3spatiotempcv,
    mlr-org/mlr3proba,
    paleolimbot/qgisprocess,
    nowosad/spDataLarge,
```

An issue associated with this is that if you run 

```
remotes::install_github("geocompr/geocompkg", dependencies = TRUE)
```

On the majority of computers that have not been authenticated with GitHub, you may get an error message along the lines of the following, if other packages have been installed from GitHub:

```
Downloading GitHub repo mlr-org/mlr3proba@HEAD
Downloading GitHub repo alan-turing-institute/distr6@HEAD
Error: Failed to install 'unknown package' from GitHub:
  Failed to install 'unknown package' from GitHub:
  Failed to install 'unknown package' from GitHub:
  Failed to install 'unknown package' from GitHub:
  HTTP error 403.
  API rate limit exceeded for 51.154.68.67. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

  Rate limit remaining: 0/60
  Rate limit reset at: 2023-05-21 12:08:42 UTC

  To increase your GitHub API rate limit
  - Use `usethis::create_github_token()` to create a Personal Access Token.
  - Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`.
```

This is not good for reproducibility, especially for beginners. Is there any way we can move away from dependency on any of these GitHub packages or can we help their maintainers submit to CRAN?

Thoughts v. welcome @jannes-m and @Nowosad or anyone.

**Comment by jannes-m** [comment]
mlr3spatiotempcv is and qgisprocess soon will be on cran. mlr3proba was removed from cran and is not likely to be uploaded again. mlr3extralearners has never been intended to live on cran. However, we need mlr3proba and mlr3extralearners for the processing. So there is not much we can do about it.

**Comment by Robinlovelace** [comment]
One option for `mlr3proba` from its README is to set repos:

```
options(repos=c(
  mlrorg = 'https://mlr-org.r-universe.dev',
  raphaels1 = 'https://raphaels1.r-universe.dev',
  CRAN = 'https://cloud.r-project.org'
))
install.packages("mlr3proba")
```

Not sure how that would work for DESCRIPTION files although the example above was from a Docker image. Overall: sounds reasonable re. `mlr3proba` and there was no way we could have known that it was going to be removed from CRAN when first using it. Are there any other packages that provide the same functionality?

It's not a big deal in any case. Great that **mlr3extralearners** and **`qgisprocess`** will be on CRAN soon.

**Comment by Robinlovelace** [comment]
Do we know where **mlr3proba** is used? I've looked in here for mention of it and searched in the repo: https://github.com/geocompx/geocompr/blob/main/12-spatial-cv.Rmd

**Comment by jannes-m** [comment]
Good question, I couldn't find it either and neither in the ecology chapter. OK, I will try to skip it, and then we'll see what happens.

**Comment by Nowosad** [comment]
Great issue, @Robinlovelace. 

I took me some time to think about it, but now I think the solution to our problem is R-universe. Try:

```
options(repos = c(
  geocompx = 'https://geocompx.r-universe.dev',
  cran = 'https://cloud.r-project.org'
))

install.packages("spDataLarge")
install.packages("geocompkg")
```

**Comment by Robinlovelace** [comment]
Great fix Jakub! 

Follow-up: should we add instructions to the geocompr README? See PR above, that should do the trick.
